- name: Install vagrant
  portinstall:
    name=vagrant
    state=present
  #changed_when: false
  when: freebsd_install_from_ports|bool
#  sudo: yes
  tags:
    - vagrant

- name: Convert package to ng
  shell: pkg2ng
  when: not freebsd_install_from_ports|bool
  changed_when: false
#  sudo: yes
  tags:
    - vagrant

- name: Install vagrant
  pkgng:
    name=vagrant
    state=present
  when: not freebsd_install_from_ports|bool
#  sudo: yes
  tags:
    - vagrant


# emulators/virtualbox-ose
- name: Install vagrant
  portinstall:
    name=virtualbox-ose
    state=present
  when: freebsd_install_from_ports|bool and enable_virtualbox|bool
#  sudo: yes
  tags:
    - vagrant

- name: Install vagrant
  pkgng:
    name=virtualbox-ose
    state=present
  when: not freebsd_install_from_ports|bool and enable_virtualbox|bool
#  sudo: yes
  tags:
    - vagrant
