- name: Install Vagrant package
  yum:
    name={{vagrant_tmp_file}}
    state=present
  changed_when: false
  when: ansible_distribution_major_version|int < 22
  tags:
    - vagrant


- name: Install Vagrant package
  shell: dnf install {{ vagrant_tmp_file }} -y
  changed_when: false
  when: ansible_distribution_major_version|int >= 22
  tags:
    - vagrant

- name: Adding virtualbox repository into sources list for Fedora
  template: src=Fedora.repo.j2 dest=/etc/yum.repos.d/virtualbox.repo
  tags:
    - vagrant



