- name: Install package
  zypper:
    name={{vagrant_tmp_file}}
    state=present
  changed_when: false
  tags:
    - vagrant

#- name: Create a repositories folder
#  file:
#    path=/etc/zypp/repos.d/
#    mode=0644
#    state=directory
#  tags:
#    - vagrant

#- name: Adding virtualbox repository into sources list for Suse 11.4/12.1/12.2.
#  template: src=Suse-11.4-12.1-12.2.repo.j2 dest=/etc/yum.repos.d/virtualbox.repo
#  when: ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse'
#  tags:
#    - vagrant



- name: Adding virtualbox repository into sources list for Suse
  template: src=Suse.repo.j2 dest=/etc/zypp/repos.d/virtualbox.repo
  changed_when: false
  tags:
    - vagrant

#- debug: msg="{{ansible_distribution_release}} ansible_distribution_version:{{ ansible_distribution_version}} System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Refresh repo
  shell: zypper  --non-interactive --no-gpg-checks --gpg-auto-import-keys refresh
  changed_when: false
  ignore_errors: yes
  tags:
    - vagrant

- name: Refresh repo
  shell: zypper  --non-interactive --gpg-auto-import-keys refresh
  changed_when: false
  ignore_errors: yes
  tags:
    - vagrant

- name: Install VirtualBox
  zypper:
    name={{item}}
    state=present
    disable_gpg_check=yes
  with_items: virutalbox_packages
  changed_when: false
  tags:
    - vagrant


