- name: Install package
  yum:
    name={{vagrant_tmp_file}}
    state=present
  changed_when: false
  tags:
    - vagrant

#- name: Adding virtualbox repository into sources list for Suse 11.4/12.1/12.2.
#  template: src=Suse-11.4-12.1-12.2.repo.j2 dest=/etc/yum.repos.d/virtualbox.repo
#  when: ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse'
#  tags:
#    - vagrant

- name: Adding virtualbox repository into sources list for Suse
  template: src=Suse.repo.j2 dest= /etc/zypp/repos.d/virtualbox.repo
  when: ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse'
  tags:
    - vagrant



