# Setup for Vagrant

- set_fact:
  vagrant_arch_ext="i686"
  when: ansible_architecture == "i386"
  tags:
    - vagrant

- set_fact:
  vagrant_arch_ext="x86_64"
  when: ansible_architecture == "x86_64"
  tags:
    - vagrant

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - vagrant

- name: Download Vagrant
  get_url: url="{{ vagrant_url }}" dest="{{vagrant_tmp_file}}" force=no validate_certs=no
  tags:
    - vagrant

- include: install-debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - vagrant



- include: install-redhat.yml
#  when: "ansible_os_family == 'Debian'"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
  tags:
    - vagrant

- include: install-fedora.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat'
  tags:
    - vagrant

- include: install-suse.yml
  when: ansible_distribution == 'SLES' or ansible_distribution == 'OES' or ansible_distribution == 'Suse'
  tags:
    - vagrant

